<a href="https://colab.research.google.com/github/Kala-Ayush/Data-Analysis/blob/main/SQL_Practice_Ayush_Kala.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# References

We are using an example SQLite database from:

  + https://www.sqlitetutorial.net/sqlite-sample-database/

## Schema Diagram



Here is the Entity Relationship Diagram (ERD) for this database:

![](https://www.sqlitetutorial.net/wp-content/uploads/2015/11/sqlite-sample-database-color.jpg)

# Setup

## Downloading the Database

Downloading the database file (then refresh the filesystem to see the "chinook.db" file):

In [ ]:
import os

DB_FILEPATH = "chinook.db"

def download_db(db_filepath=DB_FILEPATH):
    """using some terminal commands to download the .db file"""

    if os.path.isfile(db_filepath):
        print("DATABASE FILE EXISTS!")
    else:
        print("---------------")
        print("DOWNLOADING...")
        !wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

        print("---------------")
        print("UNZIPPING...")
        !unzip "/content/chinook.zip"

        print("---------------")
        print("CLEANING UP...")
        !rm "/content/chinook.zip"


download_db()
assert os.path.isfile(DB_FILEPATH)

DATABASE FILE EXISTS!

## Connecting to the Database

Depending on the type of database (e.g. SQLite, MySQL, PostgreSQL), we would use a different strategy and set of packages to connect with it.

In this case we have a SQLite database, so we can use the `sqlite` module to interface with the database in a lower-level way, or various functions from `pandas` pacakge to interface with the database in a higher-level way.

### SQLite Connection

In this section, we demonstrate our ability to connect to the database using the `sqlite` module.

In [ ]:
import sqlite3

connection = sqlite3.connect(DB_FILEPATH)
connection.row_factory = sqlite3.Row
print("CONNECTION:", connection)

CONNECTION: <sqlite3.Connection object at 0x7f2d4ff68340>

In [ ]:
cursor = connection.cursor()
print("CURSOR", cursor)

CURSOR <sqlite3.Cursor object at 0x7f2d4ff58bc0>

Example question: "Who are all our customers? What are their names?"

In [ ]:
sql = """
    SELECT *
    FROM customers;
"""
results = cursor.execute(sql).fetchall()
print("RESULTS:", len(results))
print(results)

RESULTS: 59
[<sqlite3.Row object at 0x7f2d4ff915a0>, <sqlite3.Row object at 0x7f2d4ff91990>, <sqlite3.Row object at 0x7f2d4ff90f40>, <sqlite3.Row object at 0x7f2d4ff91420>, <sqlite3.Row object at 0x7f2d4ff91180>, <sqlite3.Row object at 0x7f2d4ff90dc0>, <sqlite3.Row object at 0x7f2d4ff91030>, <sqlite3.Row object at 0x7f2d4ff90cd0>, <sqlite3.Row object at 0x7f2d4ff90d00>, <sqlite3.Row object at 0x7f2d4ff90c70>, <sqlite3.Row object at 0x7f2d4ff90d30>, <sqlite3.Row object at 0x7f2d4ff90c40>, <sqlite3.Row object at 0x7f2d4ff90d60>, <sqlite3.Row object at 0x7f2d4ff91f00>, <sqlite3.Row object at 0x7f2d4ff91a20>, <sqlite3.Row object at 0x7f2d4ff91ae0>, <sqlite3.Row object at 0x7f2d4ff90490>, <sqlite3.Row object at 0x7f2d4ff911b0>, <sqlite3.Row object at 0x7f2d4ff913c0>, <sqlite3.Row object at 0x7f2d4ff91810>, <sqlite3.Row object at 0x7f2d4ff91330>, <sqlite3.Row object at 0x7f2d4ff91360>, <sqlite3.Row object at 0x7f2d4ff90e80>, <sqlite3.Row object at 0x7f2d4ff902b0>, <sqlite3.Row object at 0x7f2d4ff918a0>, <sqlite3.Row object at 0x7f2d4ff91120>, <sqlite3.Row object at 0x7f2d4ff91ff0>, <sqlite3.Row object at 0x7f2d4ff91db0>, <sqlite3.Row object at 0x7f2d4ff91de0>, <sqlite3.Row object at 0x7f2d4ff91210>, <sqlite3.Row object at 0x7f2d4ff91870>, <sqlite3.Row object at 0x7f2d4ff912d0>, <sqlite3.Row object at 0x7f2d4ff91300>, <sqlite3.Row object at 0x7f2d4ff91390>, <sqlite3.Row object at 0x7f2d4ff91b40>, <sqlite3.Row object at 0x7f2d4ff91b10>, <sqlite3.Row object at 0x7f2d4ff914b0>, <sqlite3.Row object at 0x7f2d4ff912a0>, <sqlite3.Row object at 0x7f2d4ff91840>, <sqlite3.Row object at 0x7f2d4ff91150>, <sqlite3.Row object at 0x7f2d4ff910c0>, <sqlite3.Row object at 0x7f2d4ff901f0>, <sqlite3.Row object at 0x7f2d4ff913f0>, <sqlite3.Row object at 0x7f2d4ff90a00>, <sqlite3.Row object at 0x7f2d4ff909d0>, <sqlite3.Row object at 0x7f2d4ff917b0>, <sqlite3.Row object at 0x7f2d4ff91780>, <sqlite3.Row object at 0x7f2d4ff91750>, <sqlite3.Row object at 0x7f2d4ff91930>, <sqlite3.Row object at 0x7f2d4ff91900>, <sqlite3.Row object at 0x7f2d4ff918d0>, <sqlite3.Row object at 0x7f2d4ff91960>, <sqlite3.Row object at 0x7f2d4ff90670>, <sqlite3.Row object at 0x7f2d4ff915d0>, <sqlite3.Row object at 0x7f2d4ff906a0>, <sqlite3.Row object at 0x7f2d4ff90640>, <sqlite3.Row object at 0x7f2d4ff90610>, <sqlite3.Row object at 0x7f2d4ff90550>, <sqlite3.Row object at 0x7f2d4ff905e0>]

In [ ]:
#for row in rows[0:3]:
#    print("-----")
#    print(type(row)) #> sqlite3.Row
#    print(row)

In [ ]:
# these are the columns in the customers table
print(results[0].keys())

['CustomerId', 'FirstName', 'LastName', 'Company', 'Address', 'City', 'State', 'Country', 'PostalCode', 'Phone', 'Fax', 'Email', 'SupportRepId']

In [ ]:
dict(results[0])

{'CustomerId': 1,
 'FirstName': 'Luís',
 'LastName': 'Gonçalves',
 'Company': 'Embraer - Empresa Brasileira de Aeronáutica S.A.',
 'Address': 'Av. Brigadeiro Faria Lima, 2170',
 'City': 'São José dos Campos',
 'State': 'SP',
 'Country': 'Brazil',
 'PostalCode': '12227-000',
 'Phone': '+55 (12) 3923-5555',
 'Fax': '+55 (12) 3923-5566',
 'Email': 'luisg@embraer.com.br',
 'SupportRepId': 3}

In [ ]:
results[0]["FirstName"]

'Luís'

Roll your own dataframe:

In [ ]:
from pandas import DataFrame

records = [dict(row) for row in results]
results_df = DataFrame(records)
results_df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [ ]:
results_df[["CustomerId", "FirstName", "LastName"]]

    CustomerId  FirstName      LastName
0            1       Luís     Gonçalves
1            2     Leonie        Köhler
2            3   François      Tremblay
3            4      Bjørn        Hansen
4            5  František   Wichterlová
5            6     Helena          Holý
6            7     Astrid        Gruber
7            8       Daan       Peeters
8            9       Kara       Nielsen
9           10    Eduardo       Martins
10          11  Alexandre         Rocha
11          12    Roberto       Almeida
12          13   Fernanda         Ramos
13          14       Mark       Philips
14          15   Jennifer      Peterson
15          16      Frank        Harris
16          17       Jack         Smith
17          18   Michelle        Brooks
18          19        Tim         Goyer
19          20        Dan        Miller
20          21      Kathy         Chase
21          22    Heather       Leacock
22          23       John        Gordon
23          24      Frank       Ralston
24          25     Victor       Stevens
25          26    Richard    Cunningham
26          27    Patrick          Gray
27          28      Julia       Barnett
28          29     Robert         Brown
29          30     Edward       Francis
30          31     Martha          Silk
31          32      Aaron      Mitchell
32          33      Ellie      Sullivan
33          34       João     Fernandes
34          35   Madalena       Sampaio
35          36     Hannah     Schneider
36          37       Fynn    Zimmermann
37          38     Niklas      Schröder
38          39    Camille       Bernard
39          40  Dominique      Lefebvre
40          41       Marc        Dubois
41          42      Wyatt        Girard
42          43   Isabelle       Mercier
43          44      Terhi    Hämäläinen
44          45   Ladislav        Kovács
45          46       Hugh      O'Reilly
46          47      Lucas       Mancini
47          48   Johannes  Van der Berg
48          49  Stanisław        Wójcik
49          50    Enrique         Muñoz
50          51     Joakim     Johansson
51          52       Emma         Jones
52          53       Phil        Hughes
53          54      Steve        Murray
54          55       Mark        Taylor
55          56      Diego     Gutiérrez
56          57       Luis         Rojas
57          58      Manoj        Pareek
58          59       Puja    Srivastava

For this exercise, we'll prefer to use more specific SQL query to arrive at the answer more directly:

In [ ]:
sql = """
    SELECT DISTINCT CustomerId, firstName, lastName
    FROM customers;
"""
results = cursor.execute(sql).fetchall()
print("RESULTS:", len(results))
for row in results:
    print(row["CustomerId"], row["firstName"], row["lastName"])

RESULTS: 59
1 Luís Gonçalves
2 Leonie Köhler
3 François Tremblay
4 Bjørn Hansen
5 František Wichterlová
6 Helena Holý
7 Astrid Gruber
8 Daan Peeters
9 Kara Nielsen
10 Eduardo Martins
11 Alexandre Rocha
12 Roberto Almeida
13 Fernanda Ramos
14 Mark Philips
15 Jennifer Peterson
16 Frank Harris
17 Jack Smith
18 Michelle Brooks
19 Tim Goyer
20 Dan Miller
21 Kathy Chase
22 Heather Leacock
23 John Gordon
24 Frank Ralston
25 Victor Stevens
26 Richard Cunningham
27 Patrick Gray
28 Julia Barnett
29 Robert Brown
30 Edward Francis
31 Martha Silk
32 Aaron Mitchell
33 Ellie Sullivan
34 João Fernandes
35 Madalena Sampaio
36 Hannah Schneider
37 Fynn Zimmermann
38 Niklas Schröder
39 Camille Bernard
40 Dominique Lefebvre
41 Marc Dubois
42 Wyatt Girard
43 Isabelle Mercier
44 Terhi Hämäläinen
45 Ladislav Kovács
46 Hugh O'Reilly
47 Lucas Mancini
48 Johannes Van der Berg
49 Stanisław Wójcik
50 Enrique Muñoz
51 Joakim Johansson
52 Emma Jones
53 Phil Hughes
54 Steve Murray
55 Mark Taylor
56 Diego Gutiérrez
57 Luis Rojas
58 Manoj Pareek
59 Puja Srivastava

### Pandas Helper Functions

Or use the `pandas.read_sql_query()` function to get a dataframe:

In [ ]:
from pandas import read_sql_query

results_df = read_sql_query(sql, connection)
results_df.head()

   CustomerId  FirstName     LastName
0           1       Luís    Gonçalves
1           2     Leonie       Köhler
2           3   François     Tremblay
3           4      Bjørn       Hansen
4           5  František  Wichterlová

In [ ]:
read_sql_query("SELECT DISTINCT CustomerId, FirstName, LastName FROM customers;", connection)

    CustomerId  FirstName      LastName
0            1       Luís     Gonçalves
1            2     Leonie        Köhler
2            3   François      Tremblay
3            4      Bjørn        Hansen
4            5  František   Wichterlová
5            6     Helena          Holý
6            7     Astrid        Gruber
7            8       Daan       Peeters
8            9       Kara       Nielsen
9           10    Eduardo       Martins
10          11  Alexandre         Rocha
11          12    Roberto       Almeida
12          13   Fernanda         Ramos
13          14       Mark       Philips
14          15   Jennifer      Peterson
15          16      Frank        Harris
16          17       Jack         Smith
17          18   Michelle        Brooks
18          19        Tim         Goyer
19          20        Dan        Miller
20          21      Kathy         Chase
21          22    Heather       Leacock
22          23       John        Gordon
23          24      Frank       Ralston
24          25     Victor       Stevens
25          26    Richard    Cunningham
26          27    Patrick          Gray
27          28      Julia       Barnett
28          29     Robert         Brown
29          30     Edward       Francis
30          31     Martha          Silk
31          32      Aaron      Mitchell
32          33      Ellie      Sullivan
33          34       João     Fernandes
34          35   Madalena       Sampaio
35          36     Hannah     Schneider
36          37       Fynn    Zimmermann
37          38     Niklas      Schröder
38          39    Camille       Bernard
39          40  Dominique      Lefebvre
40          41       Marc        Dubois
41          42      Wyatt        Girard
42          43   Isabelle       Mercier
43          44      Terhi    Hämäläinen
44          45   Ladislav        Kovács
45          46       Hugh      O'Reilly
46          47      Lucas       Mancini
47          48   Johannes  Van der Berg
48          49  Stanisław        Wójcik
49          50    Enrique         Muñoz
50          51     Joakim     Johansson
51          52       Emma         Jones
52          53       Phil        Hughes
53          54      Steve        Murray
54          55       Mark        Taylor
55          56      Diego     Gutiérrez
56          57       Luis         Rojas
57          58      Manoj        Pareek
58          59       Puja    Srivastava

# Challenges

Write SQL code to answer each of the questions in Parts 1-3. Execute the queries using Python.

> NOTE: in many cases it is possible to execute a simple SQL query to grab all the data, and then use pandas to further manipulate / process the data. HOWEVER: for this exercise, we are looking for you to **arrive at the answers using SQL only**! NO pandas, except for executing the queries.

Then also tackle Part 4, which asks you to setup a new database and practice storing some example data.


## Part 1 (Basic Queries)


A) Who are our customers (include their first and last names?)

B) Which customers are from the US (include their first and last names and email addresses)?

C) Which customers are from either the US or the UK (include their first and last names and email addresses)?

D) For all customers in the US or UK, sort by country, then state (HINT: use `ORDER BY` clause).

In [ ]:
sql = """

     SELECT FirstName, LastName
     FROM customers

"""
read_sql_query(sql, connection)

    FirstName      LastName
0        Luís     Gonçalves
1      Leonie        Köhler
2    François      Tremblay
3       Bjørn        Hansen
4   František   Wichterlová
5      Helena          Holý
6      Astrid        Gruber
7        Daan       Peeters
8        Kara       Nielsen
9     Eduardo       Martins
10  Alexandre         Rocha
11    Roberto       Almeida
12   Fernanda         Ramos
13       Mark       Philips
14   Jennifer      Peterson
15      Frank        Harris
16       Jack         Smith
17   Michelle        Brooks
18        Tim         Goyer
19        Dan        Miller
20      Kathy         Chase
21    Heather       Leacock
22       John        Gordon
23      Frank       Ralston
24     Victor       Stevens
25    Richard    Cunningham
26    Patrick          Gray
27      Julia       Barnett
28     Robert         Brown
29     Edward       Francis
30     Martha          Silk
31      Aaron      Mitchell
32      Ellie      Sullivan
33       João     Fernandes
34   Madalena       Sampaio
35     Hannah     Schneider
36       Fynn    Zimmermann
37     Niklas      Schröder
38    Camille       Bernard
39  Dominique      Lefebvre
40       Marc        Dubois
41      Wyatt        Girard
42   Isabelle       Mercier
43      Terhi    Hämäläinen
44   Ladislav        Kovács
45       Hugh      O'Reilly
46      Lucas       Mancini
47   Johannes  Van der Berg
48  Stanisław        Wójcik
49    Enrique         Muñoz
50     Joakim     Johansson
51       Emma         Jones
52       Phil        Hughes
53      Steve        Murray
54       Mark        Taylor
55      Diego     Gutiérrez
56       Luis         Rojas
57      Manoj        Pareek
58       Puja    Srivastava

In [ ]:
sql = """

    SELECT FirstName, LastName, Email, Country
    FROM customers
    WHERE Country = "USA"

"""
read_sql_query(sql, connection)

   FirstName    LastName                     Email Country
0      Frank      Harris        fharris@google.com     USA
1       Jack       Smith   jacksmith@microsoft.com     USA
2   Michelle      Brooks         michelleb@aol.com     USA
3        Tim       Goyer          tgoyer@apple.com     USA
4        Dan      Miller       dmiller@comcast.com     USA
5      Kathy       Chase       kachase@hotmail.com     USA
6    Heather     Leacock        hleacock@gmail.com     USA
7       John      Gordon    johngordon22@yahoo.com     USA
8      Frank     Ralston        fralston@gmail.com     USA
9     Victor     Stevens        vstevens@yahoo.com     USA
10   Richard  Cunningham  ricunningham@hotmail.com     USA
11   Patrick        Gray      patrick.gray@aol.com     USA
12     Julia     Barnett       jubarnett@gmail.com     USA

In [ ]:
sql = """

   SELECT FirstName, LastName, Email, Country
   FROM customers
   WHERE Country = 'USA' OR Country = 'United Kingdom'

"""
read_sql_query(sql, connection)

   FirstName    LastName                     Email         Country
0      Frank      Harris        fharris@google.com             USA
1       Jack       Smith   jacksmith@microsoft.com             USA
2   Michelle      Brooks         michelleb@aol.com             USA
3        Tim       Goyer          tgoyer@apple.com             USA
4        Dan      Miller       dmiller@comcast.com             USA
5      Kathy       Chase       kachase@hotmail.com             USA
6    Heather     Leacock        hleacock@gmail.com             USA
7       John      Gordon    johngordon22@yahoo.com             USA
8      Frank     Ralston        fralston@gmail.com             USA
9     Victor     Stevens        vstevens@yahoo.com             USA
10   Richard  Cunningham  ricunningham@hotmail.com             USA
11   Patrick        Gray      patrick.gray@aol.com             USA
12     Julia     Barnett       jubarnett@gmail.com             USA
13      Emma       Jones    emma_jones@hotmail.com  United Kingdom
14      Phil      Hughes     phil.hughes@gmail.com  United Kingdom
15     Steve      Murray     steve.murray@yahoo.uk  United Kingdom

In [ ]:
sql = """

    SELECT FirstName, LastName, Email, Country, State
    FROM customers
    WHERE Country = 'USA' OR Country = 'United Kingdom'
    ORDER BY Country, State;

"""
read_sql_query(sql, connection)

   FirstName    LastName                     Email         Country State
0    Patrick        Gray      patrick.gray@aol.com             USA    AZ
1      Frank      Harris        fharris@google.com             USA    CA
2        Tim       Goyer          tgoyer@apple.com             USA    CA
3        Dan      Miller       dmiller@comcast.com             USA    CA
4    Heather     Leacock        hleacock@gmail.com             USA    FL
5      Frank     Ralston        fralston@gmail.com             USA    IL
6       John      Gordon    johngordon22@yahoo.com             USA    MA
7      Kathy       Chase       kachase@hotmail.com             USA    NV
8   Michelle      Brooks         michelleb@aol.com             USA    NY
9    Richard  Cunningham  ricunningham@hotmail.com             USA    TX
10     Julia     Barnett       jubarnett@gmail.com             USA    UT
11      Jack       Smith   jacksmith@microsoft.com             USA    WA
12    Victor     Stevens        vstevens@yahoo.com             USA    WI
13      Emma       Jones    emma_jones@hotmail.com  United Kingdom  None
14      Phil      Hughes     phil.hughes@gmail.com  United Kingdom  None
15     Steve      Murray     steve.murray@yahoo.uk  United Kingdom  None


## Part 2 (Aggregations)


A) How many customers do we have total?

B) How many customers are from the US?

C) For all US customers, how many are in each state?

D) How many customers in each country?

E) Which 5 countries have the most customers? Sort them in descending order of their customer count.

In [ ]:
sql = """

    SELECT CustomerID
    FROM customers

"""
customers = read_sql_query(sql, connection)
print("Total customers: " + str(len(customers)))

Total customers: 59

In [ ]:
sql = """

    SELECT FirstName, LastName, Email, Country
    FROM customers
    WHERE Country = "USA"

"""
customers = read_sql_query(sql, connection)
print("Total customers from USA: " + str(len(customers)))

Total customers from USA: 13

In [ ]:
sql = """

   SELECT
   State
   ,count(DISTINCT CustomerId) as customer_count
   FROM customers
   WHERE Country = 'USA'
   GROUP BY State


"""
read_sql_query(sql, connection)

   State  customer_count
0     AZ               1
1     CA               3
2     FL               1
3     IL               1
4     MA               1
5     NV               1
6     NY               1
7     TX               1
8     UT               1
9     WA               1
10    WI               1

In [ ]:
sql = """

   SELECT
   Country
   ,count(DISTINCT CustomerId) as customer_count
   FROM customers
   GROUP BY Country


"""
read_sql_query(sql, connection)

           Country  customer_count
0        Argentina               1
1        Australia               1
2          Austria               1
3          Belgium               1
4           Brazil               5
5           Canada               8
6            Chile               1
7   Czech Republic               2
8          Denmark               1
9          Finland               1
10          France               5
11         Germany               4
12         Hungary               1
13           India               2
14         Ireland               1
15           Italy               1
16     Netherlands               1
17          Norway               1
18          Poland               1
19        Portugal               2
20           Spain               1
21          Sweden               1
22             USA              13
23  United Kingdom               3

In [ ]:
sql = """

  SELECT
  Country
  ,count(DISTINCT CustomerId) as customer_count
  FROM customers
  GROUP BY Country
  ORDER BY customer_count DESC
  LIMIT 5


"""
read_sql_query(sql, connection)

   Country  customer_count
0      USA              13
1   Canada               8
2   France               5
3   Brazil               5
4  Germany               4


## Part 3 (Multi-Table / Joins)


> HINT: here is a join types reference:
>
> <img src="https://camo.githubusercontent.com/52e1d3a424ed13892b4105190cd486f320ccc98b00ba33e40e36f678f23f6c9e/68747470733a2f2f7777772e696f6e6f732e636f6d2f6469676974616c67756964652f66696c6561646d696e2f4469676974616c47756964652f53637265656e73686f74735f323031382f4f757465722d4a6f696e2e6a7067" height=300 width=550/>


A)  For each album, what is the name of the artist that produced it? Expect 347 rows (row per album).

B) For each of the 275 artists, how many albums does each have? Optionally sort the results so the artists with the most albums are first.

C) For each of the 275 artists, how many tracks does each have? Optionally sort the results so the artists with the most tracks are first.

D) Who are the ten customers who have paid the most money (include their first and last names, as well as how many invoices each has had, as well as the total invoice amount for each)?

In [ ]:
# Taken from professor's SQL document for Part 3
sql = """

  SELECT
  b.AlbumId
  , b.Title
  , b.ArtistId
  , r.Name as artist_name
  FROM albums b
  JOIN artists r ON r.ArtistId = b.ArtistId


"""
read_sql_query(sql, connection)

,AlbumId,Title,ArtistId,artist_name
0,1,For Those About To Rock We Salute You,1,AC/DC
1,2,Balls to the Wall,2,Accept
2,3,Restless and Wild,2,Accept
3,4,Let There Be Rock,1,AC/DC
4,5,Big Ones,3,Aerosmith
...,...,...,...,...
342,343,Respighi:Pines of Rome,226,Eugene Ormandy
343,344,Schubert: The Late String Quartets & String Qu...,272,Emerson String Quartet
344,345,Monteverdi: L'Orfeo,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
345,346,Mozart: Chamber Music,274,Nash Ensemble
346,347,Koyaanisqatsi (Soundtrack from the Motion Pict...,275,Philip Glass Ensemble

In [ ]:
sql = """

  SELECT
  r.ArtistId
  ,count(DISTINCT b.AlbumId) as album_count
  FROM artists r
  LEFT JOIN albums b ON r.ArtistId = b.ArtistId
  GROUP BY r.ArtistId


"""
read_sql_query(sql, connection)

     ArtistId  album_count
0           1            2
1           2            2
2           3            1
3           4            1
4           5            1
..        ...          ...
270       271            1
271       272            1
272       273            1
273       274            1
274       275            1

[275 rows x 2 columns]

In [ ]:
sql = """

  SELECT
  r.ArtistId
  ,r.Name as artist_name
  ,count(DISTINCT b.AlbumId) as album_count
  ,count(DISTINCT t.TrackId) as track_count
  FROM artists r
  LEFT JOIN albums b ON r.ArtistId = b.ArtistId
  LEFT JOIN tracks t ON t.AlbumId = b.AlbumId
  GROUP BY r.ArtistId, artist_name


"""
read_sql_query(sql, connection)

,ArtistId,artist_name,album_count,track_count
0,1,AC/DC,2,18
1,2,Accept,2,4
2,3,Aerosmith,1,15
3,4,Alanis Morissette,1,13
4,5,Alice In Chains,1,12
...,...,...,...,...
270,271,"Mela Tenenbaum, Pro Musica Prague & Richard Kapp",1,1
271,272,Emerson String Quartet,1,1
272,273,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon...",1,1
273,274,Nash Ensemble,1,1
274,275,Philip Glass Ensemble,1,1

In [ ]:
sql = """

  SELECT
  i.CustomerId
  ,c.FirstName
  ,c.LastName
  ,c.Email
  ,count(DISTINCT i.InvoiceId) as invoice_count
  ,sum(i.Total) as invoice_total
  FROM invoices i
  LEFT JOIN customers c on c.CustomerId = i.CustomerId
  GROUP BY i.CustomerId
  ORDER BY invoice_total DESC
  LIMIT 10


"""
read_sql_query(sql, connection)

,CustomerId,FirstName,LastName,Email,invoice_count,invoice_total
0,6,Helena,Holý,hholy@gmail.com,7,49.62
1,26,Richard,Cunningham,ricunningham@hotmail.com,7,47.62
2,57,Luis,Rojas,luisrojas@yahoo.cl,7,46.62
3,45,Ladislav,Kovács,ladislav_kovacs@apple.hu,7,45.62
4,46,Hugh,O'Reilly,hughoreilly@apple.ie,7,45.62
5,28,Julia,Barnett,jubarnett@gmail.com,7,43.62
6,24,Frank,Ralston,fralston@gmail.com,7,43.62
7,37,Fynn,Zimmermann,fzimmermann@yahoo.de,7,43.62
8,7,Astrid,Gruber,astrid.gruber@apple.at,7,42.62
9,25,Victor,Stevens,vstevens@yahoo.com,7,42.62

## Part 4 (Database Management)



A) **Create your own example dataset**, formatted as a list of dictionaries, and store it in a variable called `records`. It should contain around ten records or so. Choose your own topic / domain. Can use ChatGPT to help generate the examples. Create a pandas dataframe of this data, and store in a variable called `records_df`.


B) **Create / connect to a new SQLite database** to store the data. Choose your own database file name, perhaps called "exercise.db".

C) **Create a new table** in the database, using a specified schema that matches the columns / fields in your example dataset. Choose your own table name that describes the kind of records we will be storing in it. The table's schema should ideally include an auto-incrementing integer primary key called `id`, as well as an auto-generated timestamp called `created_at`.

D) **Store the records** in the designated table.

E) Execute a query to **retrieve all records from the table**, and display them, to verify the data got stored properly.

Nice!

In [ ]:
#Help taken from ChatGPT
import pandas as pd
import sqlite3
from datetime import datetime

teams_data = [
    {"TeamName": "Manchester United", "FoundedYear": 1878, "City": "Manchester"},
    {"TeamName": "Liverpool", "FoundedYear": 1892, "City": "Liverpool"},
    {"TeamName": "Chelsea", "FoundedYear": 1905, "City": "London"},
    {"TeamName": "Arsenal", "FoundedYear": 1886, "City": "London"},
    {"TeamName": "Manchester City", "FoundedYear": 1880, "City": "Manchester"},
    {"TeamName": "Tottenham Hotspur", "FoundedYear": 1882, "City": "London"},
    {"TeamName": "Leicester City", "FoundedYear": 1884, "City": "Leicester"},
    {"TeamName": "Everton", "FoundedYear": 1878, "City": "Liverpool"},
    {"TeamName": "West Ham United", "FoundedYear": 1895, "City": "London"},
    {"TeamName": "Southampton", "FoundedYear": 1885, "City": "Southampton"},
]

teams_df = pd.DataFrame(teams_data)

db_name = "soccer_teams.db"
table_name = "teams"

conn = sqlite3.connect(db_name)
cursor = conn.cursor()

table_schema = """
    CREATE TABLE IF NOT EXISTS {} (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        TeamName TEXT NOT NULL,
        FoundedYear INTEGER,
        City TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
""".format(table_name)

cursor.execute(table_schema)

teams_df.to_sql(table_name, conn, if_exists="replace", index=False)

query = "SELECT * FROM {}".format(table_name)
result = pd.read_sql(query, conn)

print(result)

conn.close()

            TeamName  FoundedYear         City
0  Manchester United         1878   Manchester
1          Liverpool         1892    Liverpool
2            Chelsea         1905       London
3            Arsenal         1886       London
4    Manchester City         1880   Manchester
5  Tottenham Hotspur         1882       London
6     Leicester City         1884    Leicester
7            Everton         1878    Liverpool
8    West Ham United         1895       London
9        Southampton         1885  Southampton